acme_store_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }

acme_store_create:
    path:     /storecreate
    defaults: { _controller: AcmeStoreBundle:Default:create }

acme_store_show:
    path:     /storeshow/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show }
