acme_form:
    resource: "@AcmeFormBundle/Resources/config/routing.yml"
    prefix:   /

acme_ui:
    resource: "@AcmeUiBundle/Resources/config/routing.yml"
    prefix:   /

acme_logger:
    resource: "@AcmeLoggerBundle/Resources/config/routing.yml"
    prefix:   /

acme_rest:
    resource: "@AcmeRestBundle/Resources/config/routing.yml"
    prefix:   /

acme_doctrine:
    resource: "@AcmeDoctrineBundle/Resources/config/routing.yml"
    prefix:   /

acme_service:
    resource: "@AcmeServiceBundle/Resources/config/routing.yml"
    prefix:   /

acme_session:
    resource: "@AcmeSessionBundle/Resources/config/routing.yml"
    prefix:   /

acme_calc:
    resource: "@AcmeCalcBundle/Resources/config/routing.yml"
    prefix:   /

