acme_rest:
    resource: "@AcmeRestBundle/Resources/config/routing.yml"
    prefix:   /

acme_doctrine:
    resource: "@AcmeDoctrineBundle/Resources/config/routing.yml"
    prefix:   /

acme_service:
    resource: "@AcmeServiceBundle/Resources/config/routing.yml"
    prefix:   /

acme_session:
    resource: "@AcmeSessionBundle/Resources/config/routing.yml"
    prefix:   /

acme_calc:
    resource: "@AcmeCalcBundle/Resources/config/routing.yml"
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

